openapi: 3.0.3
info:
  title: Health Tracker API
  description: This is an API that provides health tracker CRUD operations.
  version: 1.0.0
  contact:
    name: Divya Maria Appachan
    email: 20105240@mail.wit.ie
paths:
  /api/users/{user-id}:
    parameters:
      - $ref: '#/components/parameters/userIdParam'
    get:
      responses:
        200:
          description: This is a specific user in the app
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      description: Delete a specific user
      responses:
        204:
          description: User deleted successfully
    patch:
      description: Update a specific user
      parameters:
        - $ref: '#/components/parameters/userIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User' # Assuming you are using the same User schema for updates
      responses:
        200:
          description: User updated successfully

  /api/users:
    get:
      responses:
        200:
          description: This is a list of the users in the app
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserList'
    post:
      description: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: User created successfully
  /api/users/{user-id}/activities:
    get:
      parameters:
        - $ref: '#/components/parameters/userIdParam'
      responses:
        200:
          description: Get activities for a specific user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityList'


  /api/users/email/{email}:
    get:
      parameters:
        - $ref: '#/components/parameters/emailParam'
      responses:
        200:
          description: Get a user by email
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /api/activities:
    get:
      responses:
        200:
          description: Get a list of all activities
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityList'
    post:
      description: Create a new activity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Activity'
      responses:
        201:
          description: Activity created successfully
  /api/activities/{activity-id}:
    get:
      parameters:
        - $ref: '#/components/parameters/activityIdParam'
      responses:
        200:
          description: Get a specific activity by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
    delete:
      description: Delete a specific activity by ID
      parameters:
        - $ref: '#/components/parameters/activityIdParam'
      responses:
        204:
          description: Activity deleted successfully
    patch:
      description: Update a specific activity by ID
      parameters:
        - $ref: '#/components/parameters/activityIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Activity' # Assuming you are using the same Activity schema for updates
      responses:
        200:
          description: Activity updated successfully

components:
  parameters:
    userIdParam:
      in: path
      name: user-id
      required: true
      schema:
        type: integer
        example: 3232
    activityIdParam:
      in: path
      name: activity-id
      required: true
      schema:
        type: integer
        example: 12345
    emailParam:
      in: path
      name: email
      required: true
      schema:
        type: string
        example: joe@soap.com

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 3232
        name:
          type: string
          example: Joe Soap
        email:
          type: string
          example: joe@soap.com

    UserList:
      type: array
      items:
        $ref: '#/components/schemas/User'

    Activity:
      type: object
      properties:
        id:
          type: integer
          example: 12345
        name:
          type: string
          example: Running

    ActivityList:
      type: array
      items:
        $ref: '#/components/schemas/Activity'

  
